spring.application.name=bms_spring

spring.datasource.url=jdbc:postgresql://localhost:5432/busdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
